services:
  db:
    image: mysql:8.0
    container_name: studybuddy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studybuddy
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: studybuddy-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: studybuddy
    command: node backend/server.js